### ISSUE TITLE
New version of embed code returns non-functional iframe

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/sul-embed#881]
### Expected behavior
A user should be able to copy the embed code from the UV and embed it in a website to get a functional iframe

### Actual behavior
See below, but current embed code produces an error "The page you were looking for doesn't exist"

### Steps to reproduce the behavior
See detailed email below from external user

### Browser / Environment
Chrome (tested by me), not sure about external user.

### User feedback

The embed code for https://purl.stanford.edu/ch403gv9140
does not load.
Here's the code that I'm copying and pasting to our website:
`<iframe src="https://embed.stanford.edu/uv.html#?manifest=https://purl.stanford.edu/ch403gv9140/iiif/manifest&c=0&m=0&s=0&cv=0&config=./uv-config.json&locales=en-GB:English (GB)&xywh=-922,-53,2527,1044&r=0" width="560" height="420" allowfullscreen frameborder="0"></iframe>`

The code above generates an error message that says 

"The page you were looking for doesn't exist. You may have mistyped the address or the page may have moved. If you are the application owner check the logs for more information."

However, if I remove sections of the URL and replace it with the following, the iframe loads correctly.
`<iframe src="https://embed.stanford.edu/iframe?url=https://purl.stanford.edu/ch403gv9140" width="560" height="420" allowfullscreen frameborder="0"></iframe>
`
The code above is what that I pulled from Batch 1, in early March for Loretta Argrett: https://purl.stanford.edu/vb049xq7502. The Iframe for this particular example is much simpler. I've notice that the code for Loretta Argrett has changed in Batch2. 

So is this a bug or is can you advise on the best to make this iframe loadable onto other websites?

The web page below further illustrates the non working links vs the working links:
```
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
</head>
<body>
  <iframe src="https://embed.stanford.edu/uv.html#?manifest=https://purl.stanford.edu/ch403gv9140/iiif/manifest&c=0&m=0&s=0&cv=0&config=./uv-config.json&locales=en-GB:English (GB)&xywh=-796,0,2274,939&r=0" width="560" height="420" allowfullscreen frameborder="0"></iframe><br>https://purl.stanford.edu/ch403gv9140 Klein<br>
  <iframe src="https://embed.stanford.edu/uv.html#?manifest=https://purl.stanford.edu/vb049xq7502/iiif/manifest&c=0&m=0&s=0&cv=0&config=./uv-config.json&locales=en-GB:English (GB)&xywh=-15,-146,379,574&r=0" width="560" height="420" allowfullscreen frameborder="0"></iframe><br>https://purl.stanford.edu/vb049xq7502 Argrett<br>
  <iframe width="560" height="420" src="https://embed.stanford.edu/iframe?url=https://purl.stanford.edu/vb049xq7502" allowfullscreen="allowfullscreen" frameborder="0"></iframe><br>https://purl.stanford.edu/vb049xq7502 Argrett<br>
  <iframe src="https://embed.stanford.edu/iframe?url=https://purl.stanford.edu/ch403gv9140" width="560" height="420" allowfullscreen frameborder="0"></iframe><br>https://purl.stanford.edu/vb049xq7502 Klein<br>
</body>
</html>
```

With the following result:

![screencapture-2018-04-27](https://user-images.githubusercontent.com/796990/39388862-2d3b5b66-4a38-11e8-870c-947e4a8e431a.png)

**Comment by jkeck** [comment]
It appears as if we've lost one of our [UV customizations](https://github.com/sul-dlss/universalviewer/pull/38/commits/3698a237a23b6d243959161f0f15650a63a52c44) in a recent round of updating from upstream looking at [what we have currently](
https://github.com/sul-dlss/universalviewer/blob/7f05c0546a50af3a4c976af53d2702cbdec577f0/src/extensions/uv-seadragon-extension/Extension.ts#L890-L897).

**Comment by mejackreed** [comment]
Resolved with https://github.com/sul-dlss/sul-embed/pull/882

**Comment by camillevilla** [comment]
@blalbrit Thanks for reporting. The fix has been deployed to production and embed URLs are back to normal:
```
<iframe src="https://embed.stanford.edu/uv.html?url=https://purl.stanford.edu/ch403gv9140" width="560" height="420" allowfullscreen frameborder="0"></iframe>
```

Future-proofing work going on in:
#883
sul-dlss/universalviewer#60

**Comment by blalbrit** [comment]
Stakeholder tested this morning, and I have confirmed, that while the embed code has changed, it still does not produce a functioning iFrame.
![embed-code-from-sdr](https://user-images.githubusercontent.com/796990/39398370-884c45f4-4ac1-11e8-9d7e-be7c6fa144c8.jpg)

So:

New code (doesn't work): `https://embed.stanford.edu/uv.html?url=https://purl.stanford.edu/ch403gv9140`

Old code (does work): `https://embed.stanford.edu/iframe?url=https://purl.stanford.edu/ch403gv9140`

Only distinction appears to be the uv.html vs. iframe parts of the URL paths.
